_wandb:
    value:
        cli_version: 0.19.10
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.8.20
            "5": 0.19.10
            "8":
                - 5
            "12": 0.19.10
            "13": linux-x86_64
embedding_dim:
    value: 256
epochs:
    value: 50
hidden_dim:
    value: 512
learning_rate:
    value: 0.001
model_type:
    value: PoemLSTM
num_layers:
    value: 3
vocab_size:
    value: 8293
